### ISSUE TITLE
Getting "no such file or directory" error for BootstrapCommand

### ISSUE THREAD

**Issue by grahamsutton** [eaperezc/blacksmith#3]
Hey Enrique,

For the bootstrap command, when I run

```bash
php blacksmith bootstrap
```

I am getting the following error when running it locally in our dev environment:

```bash
PHP Warning:  copy(/Users/graham1/Documents/Projects/PHP/blacksmith/vendor/bin/blacksmith): failed to open stream: No such file or directory in /Users/graham1/Documents/Projects/PHP/blacksmith/src/Commands/BootstrapCommand.php on line 46
```

I think we need to figure out a solid way to differentiate between paths for when we're testing it locally and when we're using it directly in the project.

Or should I wait for you to configure it to packagist so we can always test blacksmith directly in an "external" app via install through composer?

**Comment by eaperezc** [comment]
Dude, wait, I'm working on it

**Comment by eaperezc** [comment]
@grahamsutt12 there you go, have fun

**Comment by grahamsutton** [comment]
Thanks, it's working now and it installs the `/commands` directory properly in the external test project's directory.
